# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag_article',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='tag_article',
            old_name='tag',
            new_name='tag_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_lang',
            field=models.CharField(default=datetime.datetime(2016, 7, 6, 16, 11, 42, 87791), max_length=50),
            preserve_default=False,
        ),
    ]
