# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_auto_20160706_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_lang',
            field=models.CharField(default=datetime.datetime(2016, 7, 6, 16, 18, 21, 567918), max_length=50),
            preserve_default=False,
        ),
    ]
