# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0003_article_article_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='propriety',
            new_name='attribute',
        ),
    ]
