# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0005_tag_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_cont',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
